# Main info
title: Gloomnight Grove
email: #roleandroflores12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog to document updates on the development of Gloomnight Grove video game.
baseurl: "" # the subpath of your site, e.g. /blog
url: "gloomnightgrove.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  roberto-leandro

# Build settings
markdown: kramdown
theme: minima

# Minima settings
minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 #- jekyll-sitemap

whitelist:
 - jekyll-feed
 - jekyll-seo-tag
 #- jekyll-sitemap

# Reading Files
include:
  - .htaccess
  - _pages
  - assets/unity
  
header_subtitle: "Development blog"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true